defaults: &defaults
  docker:
    - image: circleci/node:8.0.0
  working_directory: ~/gpustatjs




version: 2
jobs:
  deploy_it:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploy it all
          command:  |
            npm install
            npm install electron-builder@next
            npm install electron-installer-debian
            npm run release:linux
#            node build/release-to-github.js
workflows:
  version: 2
  pipeline:
    jobs:
      - deploy_it: 