machine:
  node:
    version: 8.0.0
dependencies:
  override:
    - npm install
    - npm install rimraf -g
deployment:
  release:
    tag: /v[0-9]+(\.[0-9]+)*/
    commands:
      - npm run dist
      - node ./build/release-to-github.js