defaults: &defaults
  docker:
    - image: circleci/node:8.0.0
  working_directory: ~/gpustatjs




version: 2
jobs:
  deploy_it:
    <<: *defaults
    steps:
      - run:
          name: Deploy it all
          command:  |
            npm run dist
            node build/release-to-github.js
workflows:
  version: 2
  pipeline:
    jobs:
      - deploy_it:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/